# Zjazd 3, część 2 — NumPy zaawansowane
**Autor:** [Marcin Kucharski]

In [1]:
import numpy as np

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],    # Produkt A
                  [49.99, 52.99, 47.99],    # Produkt B
                  [14.99, 15.99, 13.99],    # Produkt C
                  [99.99, 104.99, 94.99]])  # Produkt D

sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}")  # (4, 3)

Kształt macierzy: (4, 3)


In [ ]:
# Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja). Wyświetl wynik.
ceny*1.05

array([[ 31.4895,  33.5895,  30.4395],
       [ 52.4895,  55.6395,  50.3895],
       [ 15.7395,  16.7895,  14.6895],
       [104.9895, 110.2395,  99.7395]])

In [ ]:
#1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat: Centrum 10%, Galeria 5%, Online 15%.
rabaty = np.array([0.10, 0.05, 0.15])
ceny * (1-rabaty)

array([[26.991 , 30.3905, 24.6415],
       [44.991 , 50.3405, 40.7915],
       [13.491 , 15.1905, 11.8915],
       [89.991 , 99.7405, 80.7415]])

In [10]:
#Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną marżę: A=30%, B=40%, C=25%, D=50%.
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
ceny / (1+ marza)

array([[23.06923077, 24.60769231, 22.3       ],
       [35.70714286, 37.85      , 34.27857143],
       [11.992     , 12.792     , 11.192     ],
       [66.66      , 69.99333333, 63.32666667]])

In [9]:
#1d: Wyświetl najtańszy sklep dla każdego produktu.
ceny.argmin(axis=1)

array([2, 2, 2, 2])

In [11]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


In [12]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [32]:
# Masz dane o sprzedaży 6 produktów jako wektor
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
# Wiesz, że to 6 produktów × 2 miesiące

# 1. Reshape na macierz 6×2
sprzedaz = sprzedaz_flat.reshape(6,2)
# 2. Oblicz średnią sprzedaż per produkt (axis=1)
print(sprzedaz.mean(axis = 1))
# 3. Oblicz zmianę między miesiącem 1 a 2 (kolumna 1 - kolumna 0)
print(sprzedaz[:,1] - sprzedaz[:,0])

[150. 225. 215. 170. 240. 225.]
[100 150 -70 100 140 -70]


In [31]:
# Masz macierz kwartałów z zadania 2a
# 1. Spłaszcz ją z powrotem do wektora (.flatten())
kwartaly_flat = kwartaly.flatten()
# 2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
# Podpowiedź: np.concatenate([wektor, np.array([235])])
np.concatenate([kwartaly_flat, np.array([235])])

array([120, 135,  98, 142, 167, 189, 201, 178, 156, 143, 198, 221, 235])

In [33]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])

# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [40]:
npPracownicy[pensje>pensje.mean()]

array(['Jan', 'Marek', 'Zofia'], dtype='<U5')

In [44]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
print(pensje.mean())
print(np.median(pensje))
print(pensje.std())
# 2. Wyświetl imiona osób zarabiających powyżej średniej
npPracownicy = np.array(pracownicy)
print(npPracownicy[pensje>pensje.mean()])

# 3. Wyświetl imiona osób zarabiających poniżej mediany
print(npPracownicy[pensje<np.median(pensje)])
# 4. Oblicz rozstęp (max - min) i rozstęp międzykwartylowy (IQR)
print(np.max(pensje) - np.min(pensje))
print(np.percentile(pensje, 75) - np.percentile(pensje, 25))

6425.0
6050.0
1616.9029037020127
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
4900
2200.0


In [48]:
# Zasady premii:
# - ocena >= 4.5 → premia 2000 zł
# - ocena >= 4.0 → premia 1000 zł
# - ocena < 4.0 → premia 0 zł
# Podpowiedź: zagnieżdżony where:
#   np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
premia = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
# Oblicz nowe wynagrodzenie (pensja + premia)
noweWynagrodzenie = pensje + premia
# Kto dostał najwyższą premię? Użyj argmax()
print(npPracownicy[premia.argmax()])

Ewa


In [56]:
print(enumerate(kolejnosc, 1))

In [58]:
print(np.argsort(pensje)[::-1])

[3 6 1 4 7 0 2 5]


In [63]:
# Posortuj pracowników wg pensji (od najwyższej)
kolejnosc = np.argsort(pensje)[::-1]
#print(npPracownicy[kolejnosc])
#print(kolejnosc)
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]
# Wyświetl ranking: pozycja, imię, pensja, staż
# Podpowiedź: for i, idx in enumerate(kolejnosc, 1): ...
for i, idx in enumerate(kolejnosc, 1):
    print(f'{i}: {npPracownicy[idx]}, pensja: {pensje[idx]}zł, staż: {staz[idx]} lat')


1: Marek, pensja: 9100zł, staż: 15 lat
2: Zofia, pensja: 8500zł, staż: 12 lat
3: Jan, pensja: 7200zł, staż: 8 lat
4: Kasia, pensja: 6300zł, staż: 5 lat
5: Tomek, pensja: 5800zł, staż: 4 lat
6: Anna, pensja: 5500zł, staż: 3 lat
7: Ewa, pensja: 4800zł, staż: 2 lat
8: Piotr, pensja: 4200zł, staż: 1 lat


In [ ]:
# Oblicz korelację: staż vs pensja
# Podpowiedź: np.corrcoef(staz, pensje)[0, 1]
print(np.corrcoef(staz, pensje)[0, 1])
# Oblicz korelację: staż vs ocena
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)
print(np.corrcoef(staz, oceny)[0, 1])

#Staż ma mocniejszą korelację z pensją niż z oceną

0.987862864584301
0.04198471605953068


In [65]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

In [66]:
# Oblicz przychód: sprzedaz (4×6) * ceny_produktow (4,) — UWAGA na broadcasting!
# Problem: (4,6) * (4,) — nie pasuje! 6 != 4
# Rozwiązanie: ceny muszą być kolumną (4×1)
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
print(przychod)
# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)
# Który miesiąc był najlepszy łącznie? (axis=0, argmax)
# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
# Podpowiedź: przychod[:, :3].sum() vs przychod[:, 3:].sum()

[[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
