# Zjazd 3, część 1 — NumPy
**Autor:** [Marcin Kucharski]

In [86]:
import numpy as np

In [87]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [88]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [90]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [91]:
# 5. 7 równomiernych punktów od 0 do 1
procenty = np.linspace(0, 1, 7)
print(f"Procenty: {procenty}")

Procenty: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [92]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [93]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [94]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Indeksy:                     0     1    2    3    4    5    6    7    8    9   10   11
# Miesiące:                  Sty  Lut  Mar  Kwi  Maj  Cze  Lip  Sie  Wrz  Paź  Lis  Gru

In [95]:
#1.
print(miesiace_sprzedaz[0])

120


In [96]:
#2.
print(miesiace_sprzedaz[-1])

221


In [97]:
#3.
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [98]:
#4.
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [99]:
#5.
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [100]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
    [120, 145, 167],   # Produkt A
    [89,  102, 95],    # Produkt B
    [234, 267, 289],   # Produkt C
    [56,  78,  91],    # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [101]:
#1.
print(dane[0, 1])

145


In [102]:
#1.
print(dane[2])

[234 267 289]


In [103]:
#1.
print(dane[:, 0])

[120  89 234  56]


In [104]:
#1.
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


In [105]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
         'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']

ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [106]:
# Średnia cena, najdroższy produkt, najtańszy produkt
print(ceny.mean())
print(nazwy[np.argmax(ceny)]) #najdrozszy produkt
print(nazwy[np.argmin(ceny)]) # najtanszy produkt

1171.0
Laptop
Ładowarka


In [107]:
# Oblicz wartość każdego produktu (cena × ilość) i łączną wartość magazynu
wartosci = ilosci_magazyn * ceny
print(wartosci)
print(sum(wartosci))

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
549465


In [108]:
# Ceny po rabacie 15% (promocja świąteczna)
cenyRabat = ceny*0.85
# Ceny z VAT 23%
cenyVat = ceny*1.23
# Ile produktów kosztuje powyżej 1000 zł?
print(len(ceny[ceny<1000]))

6


In [109]:
# Produkty z oceną >= 4.5 — nazwy i ceny
npNazwy = np.array(nazwy)
print(npNazwy[oceny_klientow>4.5])
print(ceny[oceny_klientow>4.5])
# Produkty poniżej 200 zł — nazwy i ilości w magazynie
print(npNazwy[ceny<200])
print(ilosci_magazyn[ceny<200])

['Laptop' 'Słuchawki' 'Monitor']
[3499  349 1499]
['Ładowarka' 'Mysz']
[312 201]


In [110]:
# Produkty z niskim stanem magazynowym (< 30 szt.) — nazwy
print(npNazwy[ilosci_magazyn<30])
# Łączna wartość tych produktów
print((ceny[ilosci_magazyn<30]*ilosci_magazyn[ilosci_magazyn<30]).sum())
# Ile % całego magazynu stanowią?
print(ilosci_magazyn[ilosci_magazyn<30].sum()/ilosci_magazyn.sum()*100)

['Laptop' 'Monitor']
86962
3.819095477386935


In [111]:
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista:  61.2 ms
NumPy:  2.8 ms
NumPy jest 22× szybszy!


In [112]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista:  26.9 ms
NumPy:  1.0 ms
NumPy jest 27× szybszy!


In [113]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista:  {czas_lista*1000:.1f} ms")
print(f"NumPy:  {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista:  43.3 ms
NumPy:  2.1 ms
NumPy jest 20× szybszy!


## Wnioski z benchmarku
- NumPy jest **25×** szybszy w mnożeniu
- NumPy jest **28×** szybszy w sumowaniu
- NumPy jest **23×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list